### ISSUE TITLE
Project Logo

### ISSUE THREAD

**Issue by ScriptTiger** [UWBCD/UWBCD-Branding#2]
We need a custom project logo that we can be granted rights to for use on the website and other materials. Also, our current icon is a public domain image, so we are fine using it, but a custom one would also be nice if possible. @Tobaloidee, @Arslanshn, any ideas?

**Comment by Tobaloidee** [comment]
I can be of help of course..will make some drafts and show it here..

**Comment by ScriptTiger** [comment]
Awesome!

**Comment by Tobaloidee** [comment]
here's my design for your project @ScriptTiger  

-inspired by windows logo and a compact disc shape

![uwbcd-01-01](https://user-images.githubusercontent.com/36028424/43567018-0268f4e4-9663-11e8-9034-301f5648fac0.png)

still open for your suggestions

**Comment by ScriptTiger** [comment]
@Tobias-B-Besemer, what do you think? This will be the favicon and banner for the website.

**Comment by Tobaloidee** [comment]
If you have any specific color preferences just let me know

**Comment by ScriptTiger** [comment]
I'll wait for @Tobias-B-Besemer's opinion since he's a cofounder. But just to make sure, the logo background is transparent, right? So if we put it on top of any color it will automatically blend in? I am pretty sure most logos are like that, but I just wanted to make sure. Also, what dimensions is your image? Right now I am thinking something around 250x50px, but honestly it doesn't have to be exact, just anything around there.

**Comment by ScriptTiger** [comment]
Also, @Tobaloidee, if it helps, I would like the logo to be used at the top of these pages, it might help your color selection:
https://www.uwbcd.org/
https://www.uwbcd.org/forum/

For the forum link, your site logo will replace the "Clean Boardz" logo. But it should be able to work for the white background on the main uwbcd.org page, also. Maybe if the logo does not have a transparent background but just the light blue (#00A5FF) and white letters? So maybe forget about a transparent background? We'll see if it works.

Thanks so far, by the way. I like the Windows CD concept! I think we just have to work on the colors.

**Comment by Tobaloidee** [comment]
the final file format will be in transparent PNG, SVG and Ai . I'll wait for @Tobias-B-Besemer 's say on the design first before i make the adjustments

**Comment by ScriptTiger** [comment]
I just tested your logo with the light blue background and it actually looks pretty good. I was worried it would be hard to see, but it's not bad. So the transparency will definitely work, which is good because I will probably change the colors for the main site around later but your logo will still work.

**Comment by Tobias-B-Besemer** [comment]
Looks great! :-)

It will also be used here...
https://github.com/UWBCD
...and on sf.net...
https://sourceforge.net/projects/uwbcd-reactos/

Can we also supply a CD-Case Cover & a (simple) print to print on CD ???

**Comment by Tobias-B-Besemer** [comment]
If we get something done on Spreadshirt, I will order white shirt and black hoody... ^^ ;-)

**Comment by ScriptTiger** [comment]
I didn't think about that, but having printable materials for the CD itself is actually a pretty awesome idea.

@Tobias-B-Besemer, we may want to start a separate issue for that though because it might take longer trying to get the dimensions and everything right for the CD prints and clothing, etc., and they are bound to be more complicated and need more design since they are only images and nothing else. The website logo is just a simple image that accompanies the content of the website, so it doesn't have to be too detailed.

@Tobaloidee, if you are open to doing prints for the CD cover and CD stickers/direct CD printing, I would be totally fine if you wanted to include a small visual copyright in those cases included in the image itself, as long as it stays professional and doesn't take away from the product itself.

**Comment by Tobaloidee** [comment]
I will finalize the logo first before we move to the cd case and stickers if ever.. Are we still going to change the Logo colors? or it is already good?

**Comment by ScriptTiger** [comment]
Everything looks good to me.

**Comment by ScriptTiger** [comment]
@Tobias-B-Besemer, as soon as @Tobaloidee gets the final product rendered the first thing I'll do is replace the forum logo and let the community on Reddit know the forums are up. The forums are already open, but if we are this close to having a logo, I just want to wait until we do before drawing more traffic. Then I'll put it everywhere else it needs to be.

@Tobaloidee, you're also welcome to join us on the forums:
https://www.uwbcd.org/forum/

We could credit you as the Lead Graphic Designer. The team is pretty laid back, so you don't have to worry about any timelines or anything. We'll just send you a message from time to time as we have requests, etc., if you're up to it.

**Comment by Tobias-B-Besemer** [comment]
Was also mentioning a shirt & a hoody because of the rendering in px...
If we do, we need really high resolution...

**Comment by Tobias-B-Besemer** [comment]
Now read it all... ^^
...had some health issues...

Logo is IMHO great! :-)
SVG & Ai are great! :-) You can make a push, if you like... Also you maybe want to add a info file with link to you...

**Comment by ScriptTiger** [comment]
I am currently crediting @Tobaloidee on the forums as "Acting Lead Graphic Designer." "Acting" just means that they are filling that role but not officially in that position. If they decide to join, I can drop the "Acting," but if not they will still keep the credit. I will make a section for "Past/Inactive Team Members" so they can keep credit even after they leave.

> Acting Lead Graphic Designer
> [Tobaloidee](https://github.com/Tobaloidee)
>     - The UWBCD logos and favicons were generously provided by [Tobaloidee](https://github.com/Tobaloidee) under the [Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/) license.

**Comment by Tobaloidee** [comment]
Hi, sorry for the delay..I have been busy these days..anyways I created a PR #3 in which I uploaded the the logo files and updated the readme.. 

all of the other versions of the logo designs can be downloaded on this [LINK](https://drive.google.com/drive/folders/1_sucHOlDt8qUKzg4dWPiV3Z4ykr4OqRq)

I will be working here but i really can't commit my full time but i am very happy to help really! :)

**Comment by ScriptTiger** [comment]
@Tobaloidee, thank you much! And no worries about any commitments, we are all just doing everything in our own time as we slowly gain more interest for the project.

**Comment by ScriptTiger** [comment]
By the way, @Tobaloidee, if you saw the website, please ignore the test images I am using at the moment, I will replace them ASAP with the ones you just sent me. I had uploaded some demo ones just to test the colors, etc., and get some opinion from others.

**Comment by Tobaloidee** [comment]
Thanks @ScriptTiger and @Tobias-B-Besemer  about the CD case, do we have a dimensions for it? i'll try to make a design for it on my free time..

**Comment by Tobias-B-Besemer** [comment]
Maybe we should make an excursus about labeling software or discuss the suggested labeling software somewhere else...
UBCD has AFAIK labels... What kind of software do they suggest, if any?

**Comment by Tobias-B-Besemer** [comment]
http://www.ultimatebootcd.com/labels.html

But I think as cover a normal logo in the right dimensions are still enough...
...and the label should IMHO be without version info, so we don't need to update it much often...

**Comment by Tobias-B-Besemer** [comment]
https://www.printingforless.com/CD-Cover-Size-Specifications.html

**Comment by Tobias-B-Besemer** [comment]
I'm a nope a gfx... So I would maybe use this one...
http://www.ultimatebootcd.com/labels/label20110802.jpg
...and change head, bottom and 'User-defined' to 'ReactOS'...
Just as one 'inspiration'...
